### ISSUE TITLE
work agent immunity on when the API is unreachable and/or goes down

### ISSUE THREAD

**Issue by jparicka** [jparicka/cloudly#252]

**Comment by jparicka** [comment]
2015-05-02 15:11:08.115169 Collecting system metrics..
Traceback (most recent call last):
  File "/root/agent.py", line 486, in <module>
    main()
  File "/root/agent.py", line 478, in main
    api_response = send_data(SECRET,api_call,system_metrics)
  File "/root/agent.py", line 447, in send_data
    conn.request("POST", api_call, json.dumps(data), headers)
  File "/usr/lib/python2.7/httplib.py", line 962, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 996, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 958, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 818, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 780, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 761, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
socket.error: [Errno 111] Connection refused

**Comment by jparicka** [comment]
perhaps a better idea would be to take control over sockets, socket timeouts etc...

**Comment by jparicka** [comment]
using the os.excl()
http://stackoverflow.com/questions/11329917/restart-python-script-from-within-itself

**Comment by jparicka** [comment]
done
