### ISSUE TITLE
float division by zero on the agent swap info

### ISSUE THREAD

**Issue by jparicka** [jparicka/cloudly#263]
AGENT: v0.4.1
Written By: Jan Paricka
2015-04-02 09:52:21.255516 Collecting system metrics..
Traceback (most recent call last):
  File "/root/agent.py", line 484, in <module>
    main()
  File "/root/agent.py", line 475, in main
    system_metrics = get_system_metrics(UUID, SECRET)
  File "/root/agent.py", line 411, in get_system_metrics
    memory_usage = _get_memory_usage()
  File "/root/agent.py", line 148, in _get_memory_usage
    memory_usage['swap_used_percentage'] = round(float(mem_info[1])/float(mem_info[0])*100,2)
ZeroDivisionError: float division by zero

**Comment by jparicka** [comment]
fixed
