### ISSUE TITLE
64-bit required to run mogno (see the desc)

### ISSUE THREAD

**Issue by jparicka** [jparicka/cloudly#287]
52.17.236.83 - - [15/May/2015 15:49:38] "POST /v10/ping/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cloudly/cloudly/api.py", line 161, in ping
    networking_.insert( networking_metrics )
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 1908, in insert
    check_keys, manipulate, write_concern)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 436, in _insert
    self.codec_options, sock_info)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/pool.py", line 237, in legacy_write
    return helpers._check_gle_response(response)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/helpers.py", line 228, in _check_gle_response
    raise OperationFailure(details["err"], code, result)
OperationFailure: can't map file memory - mongo requires 64 bit build for larger datasets
^C^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/periodic_executor.py", line 139, in _shutdown_executors
    executor.join(10)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/periodic_executor.py", line 80, in join
    self._thread.join(timeout)
  File "/usr/lib/python2.7/threading.py", line 679, in join
    self.__block.wait(delay)
  File "/usr/lib/python2.7/threading.py", line 263, in wait
    _sleep(delay)
KeyboardInterrupt
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/periodic_executor.py", line 139, in _shutdown_executors
    executor.join(10)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/periodic_executor.py", line 80, in join
    self._thread.join(timeout)
  File "/usr/lib/python2.7/threading.py", line 679, in join
    self.__block.wait(delay)
  File "/usr/lib/python2.7/threading.py", line 263, in wait
    _sleep(delay)
KeyboardInterrupt

**Comment by jparicka** [comment]
oops .. wrong cp&paste but for real, you need 64 bit to store larger collection of data on mongo. full stop.

**Comment by jparicka** [comment]
acknowledged :+1:
