### ISSUE TITLE
add on exceptions handling for querying the tsdb through the vms refresh function

### ISSUE THREAD

**Issue by jparicka** [jparicka/cloudly#549]
Internal Server Error: /ajax/cloud/vms/refresh/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/cloudly/cloudly/vms/views.py", line 513, in ajax_vms_refresh
    tsdb = requests.get('http://'+settings.TSDB_HOST+':'+str(settings.TSDB_PORT)+'/api/query',params=params)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 378, in send
    raise ConnectionError(e)
ConnectionError: HTTPConnectionPool(host='31.31.74.48', port=4242): Max retries exceeded with url: /api/query?start=2m-ago&m=sum%3A52-54-00-00-42-eb.sys.cpu (Caused by <class 'socket.error'>: [Errno 104] Connection reset by peer)

**Comment by jparicka** [comment]
not applicable since this is a geniune error coming from tsdb
