### ISSUE TITLE
agent not working on redhat

### ISSUE THREAD

**Issue by jparicka** [jparicka/cloudly#61]
throws this error -

AGENT: v0.1
Written By: Jan Paricka
2015-01-27 11:24:14.779229 070-GV2L-86589 Collecting system metrics..
Traceback (most recent call last):
  File "/root/agent.py", line 320, in <module>
    system_metrics = get_system_metrics(SECRET)
  File "/root/agent.py", line 257, in get_system_metrics
    ip = _get_ip_address()
  File "/root/agent.py", line 130, in _get_ip_address
    ip = ip.group().split(':')[-1]
AttributeError: 'NoneType' object has no attribute 'group'
[root@ip-172-31-35-217 ~]#

**Comment by jparicka** [comment]
works now
