### ISSUE TITLE
os x agent crashes

### ISSUE THREAD

**Issue by jparicka** [jparicka/cloudly#775]
Traceback (most recent call last):
  File "/monitoring-agent.py", line 1016, in <module>
    main()
  File "/monitoring-agent.py", line 971, in main
    system_metrics = get_system_metrics(UUID, SECRET)
  File "/monitoring-agent.py", line 897, in get_system_metrics
    memory_usage_data, memory_usage_service_report = _get_memory_usage()
  File "/monitoring-agent.py", line 415, in _get_memory_usage
    memory_free = int(line.split(' ')[-2].replace('M',''))*1024*1000
ValueError: invalid literal for int() with base 10: '5400K'
devusertech@Jans-MacBook-Pro-3 ~>

**Comment by jparicka** [comment]
<img width="885" alt="screen shot 2016-12-01 at 9 06 48 pm" src="https://cloud.githubusercontent.com/assets/870699/20810460/1f2ce81c-b80a-11e6-85fc-ba9ddd7f300a.png">
