### ISSUE TITLE
incidents bug

### ISSUE THREAD

**Issue by jparicka** [jparicka/cloudly#786]
Internal Server Error: /ajax/incidents/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/admin/cloudly/vms/views.py", line 421, in ajax_servers_incidents
    secret = request.POST['secret']
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 322, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'secret'"
[06/Dec/2016 18:29:15] "POST /ajax/incidents/ HTTP/1.1" 500 10793

**Comment by jparicka** [comment]
to reproduce click on the incidents

**Comment by jparicka** [comment]
there is some ajax request that shouldn't be there
